#!/usr/bin/env bash
# One-command deploy: apply Terraform, then re-apply with backend/frontend URLs from outputs
# so the dashboard backend gets correct DASHBOARD_BACKEND_BASE_URL and DASHBOARD_CORS_ORIGINS.
# Run from repository root. Requires: terraform, gcloud (for auth).
#
# Usage:
#   ./scripts/deploy-gcp.sh
#   ./scripts/deploy-gcp.sh -auto-approve
#   TERRAFORM_DIR=terraform/gcp ./scripts/deploy-gcp.sh
#   WAIT_FOR_HEALTH=1 ./scripts/deploy-gcp.sh   # after apply, wait for backend /api/health (up to 120s)

set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TERRAFORM_DIR="${TERRAFORM_DIR:-terraform/gcp}"
TF_DIR="${REPO_ROOT}/${TERRAFORM_DIR}"
WAIT_FOR_HEALTH="${WAIT_FOR_HEALTH:-0}"
OVERWRITE_CONFIG_SEED="${OVERWRITE_CONFIG_SEED:-0}"

if [ ! -f "${TF_DIR}/main.tf" ]; then
  echo "Terraform dir not found: ${TF_DIR}" >&2
  exit 1
fi

cd "$TF_DIR"

CURRENT_PR_AGENT_IMAGE=$(terraform output -raw pr_agent_runner_image 2>/dev/null || true)
[ "$CURRENT_PR_AGENT_IMAGE" = "null" ] && CURRENT_PR_AGENT_IMAGE=""
PR_AGENT_VAR_ARGS=()
if [ -n "$CURRENT_PR_AGENT_IMAGE" ]; then
  PR_AGENT_VAR_ARGS=(-var="pr_agent_runner_image=$CURRENT_PR_AGENT_IMAGE")
fi

echo "=== First apply (infra + Cloud Run) ==="
terraform apply "${PR_AGENT_VAR_ARGS[@]}" "$@"

BACKEND_URL=$(terraform output -raw backend_url 2>/dev/null || true)
FRONTEND_URL=$(terraform output -raw frontend_url 2>/dev/null || true)
[ "$FRONTEND_URL" = "null" ] && FRONTEND_URL=""

if [ -n "$BACKEND_URL" ] && [ "$BACKEND_URL" != "null" ]; then
  echo "=== Second apply (inject backend/frontend URLs for CORS and links) ==="
  terraform apply "$@" \
    "${PR_AGENT_VAR_ARGS[@]}" \
    -var="backend_base_url=$BACKEND_URL" \
    -var="frontend_base_url=$FRONTEND_URL"
  echo "Done. Backend and frontend URLs are set."

  if [ "$WAIT_FOR_HEALTH" = "1" ]; then
    echo "=== Waiting for backend health (up to 120s) ==="
    for i in $(seq 1 24); do
      if curl -sf "${BACKEND_URL}/api/health" >/dev/null 2>&1; then
        echo "Backend healthy."
        break
      fi
      echo "  Attempt $i/24..."
      sleep 5
    done
    if ! curl -sf "${BACKEND_URL}/api/health" >/dev/null 2>&1; then
      echo "Warning: health check did not succeed; deployment may still be rolling out."
    fi
  fi
else
  echo "Backend URL not yet available (set backend_image and frontend_image, then apply again)."
fi

if [ "$OVERWRITE_CONFIG_SEED" = "1" ]; then
  CONFIG_BUCKET=$(terraform output -raw config_bucket 2>/dev/null || true)
  if [ -n "$CONFIG_BUCKET" ] && [ "$CONFIG_BUCKET" != "null" ]; then
    echo "Overwriting GCS config seed files (requested by OVERWRITE_CONFIG_SEED=1)..."
    gcloud storage cp "${TF_DIR}/config-seed/configuration.toml" "gs://${CONFIG_BUCKET}/pr-agent-config/configuration.toml"
    gcloud storage cp "${TF_DIR}/config-seed/secrets.toml" "gs://${CONFIG_BUCKET}/pr-agent-config/secrets.toml"
  else
    echo "Warning: OVERWRITE_CONFIG_SEED=1 was set, but config_bucket output is empty."
  fi
fi

CONFIG_BUCKET=$(terraform output -raw config_bucket 2>/dev/null || true)
CONFIG_PREFIX=$(terraform output -raw config_prefix 2>/dev/null || true)
if [ -n "$CONFIG_BUCKET" ] && [ "$CONFIG_BUCKET" != "null" ]; then
  echo ""
  echo "=== Shared config (GCS) ==="
  echo "Dashboard backend uses GCS for config automatically (PR_AGENT_CONFIG_GCS_BUCKET/PREFIX set by Terraform)."
  echo "For PR-Agent (pipeline, Cloud Run job, or VM), set the same env so it uses dashboard-edited config:"
  echo "  PR_AGENT_CONFIG_GCS_BUCKET=$CONFIG_BUCKET"
  echo "  PR_AGENT_CONFIG_GCS_PREFIX=$CONFIG_PREFIX"
fi

# Print API key (auto-generated by Terraform if not in tfvars) so user can set it in PR-Agent
API_KEY=$(terraform output -raw dashboard_api_key 2>/dev/null || true)
if [ -n "$API_KEY" ] && [ "$API_KEY" != "null" ]; then
  echo ""
  echo "=== DASHBOARD_API_KEY (set in PR-Agent / pipelines so they can post jobs and logs) ==="
  echo "Terraform generated this key and injected it into the backend. Set it in PR-Agent env or pipeline secrets:"
  echo "  DASHBOARD_API_KEY=$API_KEY"
  echo "(Store securely; e.g. GitHub Actions secret or Azure DevOps variable.)"
fi

echo ""
echo "=== Runner VMs ==="
echo "GCP_RUNNER_* are set by Terraform; use 'Provision runner VM' in the dashboard when adding a repo with a self-hosted runner connection."
